services:
  ns2:
    build: .
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    # This keeps the container's bash shell alive if started in the background
    tty: true
    stdin_open: true
