services:
  ns2:
    build: .
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    # Keep the bash shell alive when started in background
    tty: true
    stdin_open: true
