# @package _group_
device: "cuda"
init_from: "scratch"     
save_checkpoint: False
eval_interval: 10000
log_interval: 10         # Wandb logs the norms every 10 steps so it's not too spammy
eval_iters: 0
max_iters: 200
warmup_iters: 0          
lr_decay_iters: 200
overfit_single_batch: False
loss_analysis_run: False
gradient_analysis_run: True
