name: "mls_eng"
source: "parler-tts/mls_eng"
train_split: "train"                # or "train[:50%]" for a smaller subset
dev_split: "dev"
test_split: "test"
text_column: "transcript"
audio_column: "audio"
filter_column: null
filter_substring: null
token_vocabulary_path: null
