num_proc_pitch: 4
num_proc_phonemize: 24
num_proc_tokenize: 4
num_workers: 8
sampling_rate: 24000
shuffle: True
resample_on_the_fly: True
drop_last: True             # Warning: False can cause graph recompiles for incomplete batches
bucket_mapping:
  - { audio_length: 281600, phoneme_length: 260, batch_size: 91 }   # 11.7s · 880 fr · batch×fr ≈ 80.1k
  - { audio_length: 320000, phoneme_length: 290, batch_size: 80 }   # 13.3s · 1000 fr · batch×fr ≈ 80.0k
  - { audio_length: 358400, phoneme_length: 340, batch_size: 72 }   # 14.9s · 1120 fr · batch×fr ≈ 80.6k
  - { audio_length: 396800, phoneme_length: 380, batch_size: 64 }   # 16.5s · 1240 fr · batch×fr ≈ 79.4k
  - { audio_length: 437760, phoneme_length: 400, batch_size: 58 }   # 18.2s · 1368 fr · batch×fr ≈ 79.3k
  - { audio_length: 481280, phoneme_length: 440, batch_size: 53 }   # 20.1s · 1504 fr · batch×fr ≈ 79.7k
