
# NOTE: This config is specifically for the gradient_analysis run.
# The batch sizes are intentionally set very low to leave VRAM headroom

num_proc_phonemize: 12
num_proc_tokenize: 4
num_workers: 4
sampling_rate: 24000
shuffle: True
resample_on_the_fly: True
drop_last: True
bucket_mapping:
  - { audio_length: 32000,  phoneme_length: 100, batch_size: 4 } # ~1s
  - { audio_length: 80000,  phoneme_length: 200, batch_size: 4 } # ~3s
  - { audio_length: 160000, phoneme_length: 350, batch_size: 2 } # ~6s
  - { audio_length: 240000, phoneme_length: 500, batch_size: 2 } # ~10s
  - { audio_length: 384000, phoneme_length: 650, batch_size: 1 } # ~16s
  - { audio_length: 720000, phoneme_length: 900, batch_size: 1 } # ~30s
