device: "cuda"
init_from: "scratch"     # 'scratch' or 'resume'
save_checkpoint: False   # No need to checkpoint a dummy test
eval_interval: 10000     # By disabling checkpoints, we skip the eval loop anyway
log_interval: 10
eval_iters: 0
max_iters: 500           # Short run to observe rapid overfitting
warmup_iters: 0          # No warmup needed for overfit
lr_decay_iters: 500
overfit_single_batch: True
loss_analysis_run: False
gradient_analysis_run: False
