defaults:
  - _self_

training:
  device: "auto"
  learning_rate: 0
  epochs: 0

data:
  batch_size: 4
  num_proc: 4
  sampling_rate: 24000
  shuffle: true

model:
  # global model parameters
  dim_hidden: 512
  rope_base: 10000.0
  rope_max_seq_len: 3000
  min_prompt_pct: 0.2        # minimum percentage of the audio used as prompt (only training)
  max_prompt_pct: 0.5        # maximum percentage of the audio used as prompt (only training)

  # Modul: Log Mel Spectrogram Generator
  mel:
    n_fft: 1024
    hop_length: 320
    n_mels: 80
    f_min: 0.0
    f_max: null
  
  # Modul: Phoneme Encoder
  phoneme_encoder:
    transformer_layers: 6
    attention_heads: 8
    conv1d_filter_size: 2048
    conv1_kernel_size: 9
    dropout: 0.2

  # Modul: Aligner
  aligner:
    attn_channels: 80
    temperature: 0.0005
    prior_w: 1.0
